### ISSUE TITLE
Pipeline script Publish stage does not work if Azure function is not existing.

### ISSUE THREAD

**Issue by vinishgeorge** [VSChina/odd-or-even-function#4]
The publish stage fails azureFunctionAppPublish command does not publish if the function does not exists on the azure portal
The following error is displayed
Function App XXXXX-functions-name in resource group xxx-resource-group-name not found

**Comment by gavinfish** [comment]
The function plugin only takes care of deployment. So you should manage the resource(function) by yourself.

**Comment by vinishgeorge** [comment]
Thank you for the quick reply .

So the function will not be deployed if the function does not already exists ? Like in the azure-functions:deploy it creates the function it does not exist .

**Comment by gavinfish** [comment]
No, it won't. You can use Azure CLI or tools like Ansible/Terraform to manage your resources. They can provide detailed configuration to decide what your created function like.

**Comment by vinishgeorge** [comment]
Okay, thank you so much for your support. The only thing is in maven we have already mentioned the configuration I need to create the function it would have been great if the azureFunctionAppPublish would have done that for me like the mvn azure-functions:deploy does for me. 
Probably not part of this tutorial. Because in real-world the whole build and deployment should be part of the same pipeline. So like you hinted there will be another stage where we will be checking if the function exists and create it using Azure CLI and then publish the actual code in the publish stage.
